# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  catalog.api:
    build:
      context: "/home/sparanzza/Code/sandbox/EShopMicroservices/src"
      dockerfile: "Services/Catalog/CatalogAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/CatalogAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/home/sparanzza/Code/sandbox/EShopMicroservices/src/Services/Catalog/CatalogAPI:/app:rw"
    - "/home/sparanzza/Code/sandbox/EShopMicroservices/src:/src:rw"
    - "/home/sparanzza/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
