# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  basket.api:
    build:
      context: "/home/sparanzza/Code/sandbox/EShopMicroservices/src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "/home/sparanzza/Code/sandbox/EShopMicroservices/src/Services/Basket/Basket.API:/app:rw"
    - "/home/sparanzza/Code/sandbox/EShopMicroservices/src:/src:rw"
    - "/home/sparanzza/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  catalog.api:
    build:
      context: "/home/sparanzza/Code/sandbox/EShopMicroservices/src"
      dockerfile: "Services/Catalog/CatalogAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/CatalogAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/home/sparanzza/Code/sandbox/EShopMicroservices/src/Services/Catalog/CatalogAPI:/app:rw"
    - "/home/sparanzza/Code/sandbox/EShopMicroservices/src:/src:rw"
    - "/home/sparanzza/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "/home/sparanzza/Code/sandbox/EShopMicroservices/src"
      dockerfile: "Services/Discount/Discount.Grpc/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app-1/bin/Debug/net9.0/Discount.Grpc.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discount.grpc:dev"
    ports: []
    volumes:
    - "/home/sparanzza/Code/sandbox/EShopMicroservices/src/Services/Discount/Discount.Grpc:/app-1:rw"
    - "/home/sparanzza/Code/sandbox/EShopMicroservices/src:/src:rw"
    - "/home/sparanzza/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app-1"
