@CatalogAPI_HostAddress = https://localhost:6060
@productId = 0197dc3f-2cc5-4c8e-bd59-57e553bada2c
@category = customer

GET {{CatalogAPI_HostAddress}}/products
Accept: application/json

###

GET {{CatalogAPI_HostAddress}}/products/{{productId}}
Accept: application/json

###


GET {{CatalogAPI_HostAddress}}/products?pageNumber=2&pageSize=2
Accept: application/json

###


GET {{CatalogAPI_HostAddress}}/products/category/{{category}}
Accept: application/json

###

DELETE {{CatalogAPI_HostAddress}}/products/{{productId}}
Accept: application/json

###

POST {{CatalogAPI_HostAddress}}/products
Content-Type: application/json
Accept: application/json

{
  "Name": "",
  "Description": "A sample product description",
  "Price": 19.99,
  "ImageFile" : "sample_image.jpg",
  "Categories": ["another", "customer"]
}

###

PUT {{CatalogAPI_HostAddress}}/products
Content-Type: application/json
Accept: application/json

{
  "Id": "{{productId}}",
  "Name": "2 Update Sample Product 3",
  "Description": "Update  A sample product description",
  "Price": 99.99,
  "ImageFile" : "Update_sample_image.jpg",
  "Categories": ["Update", "customer"]
}


###

GET {{CatalogAPI_HostAddress}}/health
Accept: application/json

###