@CatalogAPI_HostAddress = https://localhost:5050
@productId = 0197d974-7c10-49d5-8c54-2c7918605932
@category = customer

GET {{CatalogAPI_HostAddress}}/products
Accept: application/json

###

GET {{CatalogAPI_HostAddress}}/products/{{productId}}
Accept: application/json

###


GET {{CatalogAPI_HostAddress}}/products/category/{{category}}
Accept: application/json

###

POST {{CatalogAPI_HostAddress}}/products
Content-Type: application/json
Accept: application/json

{
  "Name": "Sample Product 3",
  "Description": "A sample product description",
  "Price": 19.99,
  "ImageFile" : "sample_image.jpg",
  "Categories": ["another", "customer"]
}