version: '3.8'

services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
    
